= Spring Cloud Stream Script Transform Processor

A *Spring Cloud Stream* module that transforms messages using a script. The language of the script can be specified.

== Requirements

* Java 7 or Above

== Code Tour

ScriptTransformProcessorApplication:: the Spring Boot Main Application
ScriptTransformProcessor:: the actual module code that interacts with message channels
ScriptTransformProcessorProperties:: defines the configuration properties that are available to the Script Transform Processor
  * script: the textual form of the script to run
  * language: what language is the script? e.g. groovy/js (default groovy)
  * variables: variable bindings as a comma delimited string of name-value pairs, e.g. 'foo=bar,baz=car'
  * variablesLocation: the location of a properties file containing custom script variable bindings

## Building with Maven

```
$> mvn package
```

## Running the Application

```
$> java -jar target/script-transform-processor-${version}-exec.jar
```

## Installing in Spring Cloud Dataflow

```
XD> module register --name scripty --coordinates org.springframework.cloud.stream.module:script-transform-processor:jar:exec:1.0.0.BUILD-SNAPSHOT --type processor
```

## Using in a Spring Cloud Dataflow stream definition

```
XD> stream create --deploy true --name demo --definition "time | scripty --script=\"return payload+'::'+payload\" | log"
```

```
XD> stream create --deploy true --name demo2 --definition "time | scripty --script=\"function double(a) { return a+''+a;} double(payload);\" --language=js | log"
```
